### ISSUE TITLE
Integration with different camera 

### ISSUE THREAD

**Issue by metalaman** [TsotsosLab/fallen-person-detector#1]
Hi,

I have a regular 2D camera and an ASUS Xtion 3D sensor, Can you help me with their integration in your code for Real-Time Fall Detection.

Thanks

**Comment by solbach** [comment]
Hi!
the integration should be rather straightforward. All the system needs is a depth map and a corresponding RGB image. 
Please let me know which exact ASUS Xtion 3D sensor you have.

**Comment by metalaman** [comment]
Hi,
My RGB Camera is an OV5640 and 3D sensor is [this](https://www.asus.com/3D-Sensor/Xtion/).
I'm figuring out a way to compile openpose for Ubuntu 16 successfully. 
Will let you know once I face any problems with the integration.

Closing the issue for now.
Thanks

**Comment by metalaman** [comment]
Hi, could you help me with the integration of new camera.
