### ISSUE TITLE
fallen-person-detector keeps giving segmentation fault when it detects a person

### ISSUE THREAD

**Issue by yxchng** [TsotsosLab/fallen-person-detector#3]
Hi, 

I got the following error when I run your fallen-person-detector. Do you have any idea why the following error occurs? 

![screenshot from 2018-03-19 16-44-51](https://user-images.githubusercontent.com/10518587/37585700-f6ebceb8-2b94-11e8-8d03-1035b6bcdbaf.png)

![screenshot from 2018-03-19 16-51-03](https://user-images.githubusercontent.com/10518587/37585946-c7db813a-2b95-11e8-808c-deb76c43b33d.png)

**Comment by solbach** [comment]
Hi!
Thanks for the interest in this project. Unfortunately, I am busy with other projects these days but _**this project is not dead**_ and I try my best to dedicate time to it. :tada:.
The mistake you are getting can be traced back to _pcl_util.cpp_ line 255 

> (hull.reconstruct(cloud_convex);).

 Uncomment this for now until I found a solution. _libpcl_ is probably doing something weird here.
If you don't mind, please provide me with your exact OS, libs versions.

Thanks!

**Comment by solbach** [comment]
Hi!
Thanks for the interest in this project. Unfortunately, I am busy with other projects these days but _**this project is not dead**_ and I try my best to dedicate time to it. :tada:.
The mistake you are getting can be traced back to _pcl_util.cpp_ line 255 

> hull.reconstruct(cloud_convex);

 Uncomment this for now until I found a solution. _libpcl_ is probably doing something weird here.
If you don't mind, please provide me with your exact OS, libs versions.

Thanks!

**Comment by yxchng** [comment]
@solbach Thanks for the response. I am using Ubuntu 16.04. What lib versions you want to know? I am not sure what libs are used.

**Comment by solbach** [comment]
_PCL_ version installed, _ROS_ version, etc. 
Thanks!

**Comment by solbach** [comment]
Closed due to inactivity.
